### ISSUE TITLE
unresolved import `crate`

### ISSUE THREAD

**Issue by ether-genius** [ether-genius/pump_samrt_Contract#2]
error[E0432]: unresolved import `crate`
  --> programs\pump\src\lib.rs:17:1
   |
17 | #[program]
   | ^^^^^^^^^^
   | |
   | unresolved import
   | help: a similar path exists: `crate::instructions::__client_accounts_create_liquidity_pool`
   |
   = note: this error originates in the attribute macro `program` (in Nightly builds, run with -Z macro-backtrace for more info)
please check this issue.

**Comment by tentwinkle** [comment]
run mainnet lunch

**Comment by Luis-David95** [comment]
your advice is helpful

**Comment by ether-genius** [comment]
> run mainnet lunch
